{% set name = "crispr" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/omniscoder/crispr-gpu.git
  git_rev: v{{ version }}

build:
  number: 0

outputs:
  - name: {{ name }}-cpu
    script: SKBUILD_CONFIGURE_OPTIONS="-DCRISPR_GPU_ENABLE_CUDA=OFF" python -m pip install . --no-deps --ignore-installed -vv
    requirements:
      host:
        - python >=3.9
        - pip
        - scikit-build-core
        - cmake
        - ninja
      run:
        - python >=3.9
    about:
      summary: CPU build of crispr (CUDA disabled)

about:
  home: https://github.com/omniscoder/crispr-gpu
  license: MIT
  license_file: LICENSE
  summary: CUDA-accelerated CRISPR off-target search with MIT/CFD scoring

extra:
  recipe-maintainers:
    - omnis-coder
